apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-simple-website
  template:
    metadata:
      labels:
        app: my-simple-website
    spec:
      containers:
        - name: my-simple-website
          image: beniol/my-simple-website:latest
          ports:
            - containerPort: 80
